name: creat_s3_resources
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
jobs:
  build2_s3:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.1.9
      - name: terraform init
       run: |
          terraform init
      - name: terraform validate
        run: |
          terraform validate 
      - name: terraform plan
        run: |
          terraform plan
      - name: terraform apply -auto-approve
        run: |
          terraform apply -auto-approve
      - name: terraform destroy
        run: |
          terraform destroy -auto-approve
      

jobs:
  build2_s3:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: terraform init
        run: |
          terraform init
      - name: terraform validate
        run: |
          terraform validate 
      - name: terraform plan
        run: |
          terraform plan
      - name: terraform apply -auto-approve
        run: |
          terraform apply -auto-approve
      - name: terraform destroy
        run: |
          terraform destroy -auto-approve


