name: s3_workflow
on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build_s3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: terraform init
        run: |
          terraform init
      - name: terraform validate
        run: |
          terraform validate
      - name: terraform plan
        run: |
          terraform plan
      - name: terraform apply -auto-approve
        run: |
          terraform apply -auto-approve
      - name: terraform destroy -auto-approve
        run: |
          terraform destroy -auto-approve