
name: creat_s3_resources
on:
  workflow_dispatch:

jobs:
  build2_s3:
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY_ID}}
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: terraform init
        run: |
          terraform init
      - name: terraform validate
        run: |
          terraform validate 
      - name: terraform plan
        run: |
          terraform plan
      - name: terraform apply -auto-approve
        run: |
          terraform apply -auto-approve
      - name: terraform destroy
        run: |
          terraform destroy -auto-approve